testview/testview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('viewthis.urls')),
    path('user/', include('user.urls'))
]

testview/user/urls.py
from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
	path('login.html', views.loginView, name='login'),
	path('register.html', views.registerView, name='register'),
	path('setpassword.html', views.setpasswordView, name = 'setpassword'),
	path('login.html', views.logoutView, name='logout'),
	path('', views.index),
	path('findPassword.html', views.findPassword, name='findPassword'),
	#path('findPasswordVeri.html', views.findPasswordVeri, name='findPasswordVeri')
	path('admin/', admin.site.urls),
	path('registerForm', views.registerFormView),
	path('loginPerm', views.loginPerm, name='loginPerm'),
	path('registerPerm', views.registerPerm, name='registerPerm'),
	path('logoutPerm', views.logoutPerm, name='logoutPerm'),
	path('indexPerm', views.indexPerm),
]

testview/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class MyUser(AbstractUser):
	qq = models.CharField('qq号码', max_length=16)
	weChat = models.CharField('微信号码', max_length=100)
	mobile = models.CharField('手机号码', max_length=11)

	def __str__(self):
		return self.username

testview/viewthis/models.py
from django.utils.html import format_html
from django.db import models

# Create your models here.
class Type(models.Model):
	id = models.AutoField(verbose_name='序号',primary_key=True)
	type_name = models.CharField(verbose_name='产品类型',max_length=20)

	def __str__(self):
		return self.type_name

class Product(models.Model):
	id = models.AutoField('序号',primary_key=True)
	name = models.CharField('名称',max_length=50)
	weight = models.CharField('重量',max_length=20)
	size = models.CharField('尺寸',max_length=20)
	type = models.ForeignKey(Type, on_delete = models.CASCADE)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = '产品信息'
		verbose_name_plural = '产品信息'
		permissions = (('visit_product','Can visit Product'),)

	def get_readonly_fields(self, request, obj=None):
		if request.user.is_superuser:
			self.readonly_fields = []
		return self.readonly_fields

	def colored_type(self):
		if 'V1' in self.type.type_name:
			color_code = 'red'
		elif 'V2' in self.type.type_name:
			color_code = 'blue'
		elif 'V3' in self.type.type_name:
			color_code = 'Blue'
		else:
			color_code = 'Yellow'
		return format_html('<span style="color: {};">{}</span>', color_code, self.type,)

	colored_type.short_description='带颜色的产品类型'

class Performer(models.Model):
	id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=20)
	nationality = models.CharField(max_length=20)
	masterpiece = models.CharField(max_length=50)

class Performer_info(models.Model):
	id = models.IntegerField(primary_key=True)
	performer = models.OneToOneField(Performer, on_delete=models.CASCADE)
	birth = models.CharField(max_length=20)
	elapse = models.CharField(max_length=20)

class Program(models.Model):
	id = models.IntegerField(primary_key=True)
	performer = models.ForeignKey(Performer, on_delete=models.CASCADE)
	name = models.CharField(max_length=20)

class ProgramAnother(models.Model):
	id = models.IntegerField(primary_key=True)
	performer = models.ManyToManyField(Performer)

testview/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required, permission_required
from .form import MyUserCreationForm
import random
from .models import MyUser
# Create your views here.
def loginView(request):
	title = '登陆'
	unit_2 = '/user/register.html'
	unit_2_name = '立即注册'
	unit_1 = '/user/setpassword.html'
	unit_1_name = '修改密码'
	if request.method == 'POST':
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		if User.objects.filter(username=username):
			user = authenticate(username=username, password=password)
			if user:
				if user.is_active:
					login(request, user)
				return redirect('/user')
			else:
				tips='账号密码错误，请重新输入'
		else:
			tips = '用户不存在，请注册'
	return render(request, 'user.html', locals())

def index(request):
	username = request.user.username
	return render(request,'index.html',locals())

@login_required(login_url='/user/loginPerm')
@permission_required(perm='indexPerm.visit_Product', login_url='/user/loginPerm')
def indexPerm(request):
	user = request.user
	if user.has_perm('indexPerm.visit_Product'):
		return render(request, 'indexPerm.html', locals())
	else:
		return redirect('login.html')

def registerView(request):
	title = '注册'
	unit_2 = '/user/login.html'
	unit_2_name = '立即登陆'
	unit_1 = '/user/setpassword.html'
	unit_1_name = '修改密码'
	if request.method == 'POST':
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		if User.objects.filter(username=username):
			tips = '用户已存在'
		else:
			user = User.objects.create_user(username=username, password=password)
			user.save()
			tips = '注册成功，请登陆'
	return render(request, 'user.html', locals())

def registerFormView(request):
	if request.method == 'POST':
		user = MyUserCreationForm(request.POST)
		if user.is_valid():
			user.save()
			tips = '注册成功'
			user = MyUserCreationForm()
	else:
		user = MyUserCreationForm()
	return render(request, 'userForm.html', locals())

def setpasswordView(request):
	title = '修改密码'
	unit_2 = '/user/login.html'
	unit_2_name = '立即登陆'
	unit_1 = '/user/register.html'
	unit_1_name = '立即注册'
	new_password = True
	if request.method == 'POST':
		username = request.POST.get('username','')
		old_password = request.POST.get('password','')
		new_password = request.POST.get('new_password','')
		if User.objects.filter(username=username):
			user = authenticate(username=username, password=old_password)
			user.set_password(new_password)
			user.save()
			tips = '密码修改成功'
		else:
			tips = '用户不存在'
	return render(request, 'user.html', locals())

def setpasswordView_1(request):
	if request.method == 'POST':
		username = request.POST.get('username','')
		old_password = request.POST.get('password','')
		new_password = request.POST.get('new_password','')

		user = User.objects.filter(username=username)
		if User.objects.filter(username=username):
			user = authenticate(new_password,None,'pbkdf2_sha256')
			user.password=dj_ps
			huser.save()
	return render(request, 'user.html', locals())


def logoutView(request):
	logout(request)
	return redirect('/user')

def findPassword(request):
	button = '获取验证码'
	new_password = False
	if request.method == 'POST':
		username = request.POST.get('username','root')
		VerificationCode = request.POST.get('VerificationCode','')
		password = request.POST.get('password','')
		user = User.objects.filter(username=username)

		if not user:
			tips = '用户' + username + '不存在'
		else:
			if not request.session.get('VerificationCode',''):
				button = '重置密码'
				tips = '验证码已发送'
				new_password = True
				VerificationCode = str(random.randint(1000,9999))
				request.session['VerificationCode'] = VerificationCode
				print(VerificationCode)
				#user[0].email_user('找回密码',VerificationCode)
			elif VerificationCode == request.session.get('VerificationCode'):
				dj_ps = make_password(password, None, 'pbkdf2_sha256')
				user[0].password = dj_ps
				user[0].save()
				del request.session['VerificationCode']
				tips = '密码已重置'
			else:
				tips = '验证码错误，请重新获取'
				new_password = False
				del request.session['VerificationCode']
	return render(request,'userPara.html',locals())

def loginPerm(request):
	tips = '请登录'
	title = '用户登录'
	if request.method == 'POST':
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		if MyUser.objects.filter(username=username):
			user = authenticate(username=username, password=password)
			if user:
				if user.is_active:
					login(request, user)
				return redirect('/user/indexPerm')
			else:
				tips = '账号密码错误，请重新输入'
		else:
			tips = '用户不存在，请注册'
	return render(request, 'userPerm.html', locals())

def registerPerm(request):
	title = '用户注册'
	if request.method == 'POST':
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		if MyUser.objects.filter(username=username):
			tips = '用户已存在'
		else:
			user = MyUser.objects.create_user(username=username, password=password)
			user.save()
			permission = Permission.objects.filter(codename='visit_Product')[0]
			user.user_permissions.add(permission)
			return redirect('/user/login.html')
	return render(request, 'userPerm.html', locals())

def logoutPerm(request):
	logout(request)
	return redirect('/user/indexPerm')

testview/user/templates/filter.html
{% load myfilter %}
<html>
	<header><title>{{title|myreplace}}</title></header>
	<body>
		<p>{{ okok.a }}</p>
		{% for man in manman %}
			<p>{{ man }}</p>
		{% endfor %}

		{% if woman %}
		<p>woman shown</p>
		{% else %}
		<p>Default</p>
		{% endif %}

		<form action="">
			{% csrf_token %}
		</form>

		<a href="{% url 'filterFunc' %}">click</a>
		{% with manm=man %}
		<p>{{manm}}</p>
		{% endwith %}

		{% load staticfiles%}

		{% for name in name_list %}
		{% for ok in ok_list %}
		<p>{{ forloop.parentloop }}</p>
		{% endfor %}

		{% if forloop.counter == 1 %}
		<span>first loop</span>
		{% elif forloop.revcounter == 2 %}
		<p>倒数第二个循环</p>
		{% elif forloop.last %}
		<p>这是最后一次循环</p>
		{% else %}
		<p>本次循环次数为{{forloop.counter0}}</p>
		{% endif %}
		{% endfor %}
	</body>
</html>

testview/user/templates/indexPerm.html
<html>
	<header id="top">
		<div class="top_box">
			<ul class="lf">
				<li><a href="#">OK Official Site</a></li>
				<li><a href="#">OK2</a></li>
			</ul>
			<ul class="rt">
				{% if user.is_authenticated %}
					<li>用户名：{{ user.username }}</li>
					<li><a href="{% url 'logoutPerm' %}">退出登录</a></li>
				{% endif %}

				{% if perms.index.add_product %}
					<li>添加产品信息</li>
				{% endif %}
			</ul>
		</div>
	</header>
</html>

testview/user/templates/index_view.html
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
</head>
<body>
	<ul id="cate_box" class="lf">
		{% for type in type_list %}
		<li>
			<h3><a href="#">{{type.type}}</a></h3>
			<p>
				{% for name in name_list %}
					{% if name.type == type.type %}
						<span>{{ name.name }}</span>
					{% endif %}
				{% endfor %}
			</p>
		</li>
		{% endfor %}
	</ul>
</body>
</html>

testview/user/templates/inherite.html
{% extends "many.html" %}
{% block body %}
<p>just a test</p>
{% endblock %}

testview/user/templates/many.html
{% load myfilter %}
<!DOCTYPE html>
<html>
<head>
	<title>test</title>
</head>
<body>
	{{ four }}
	{{ five }}
	{{ six }}
	{% block body%}{% endblock %}
</body>
</html>

testview/user/templates/three.html
<!DOCTYPE html>
<html>
<head>
	<title>three</title>
</head>
<body>
	<a href="{% url 'threepara' 2018 %}">link {{ threepara }}</a>
</body>
</html>

testview/user/templates/user.html
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link rel="stylesheet" type="text/css" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
	<div class="flex-center">
		<div class="container">
			<div class="flex-center">
				<div class="unit-1-2 unit-1-on-mobile">
					<h1>MyDjango Auth</h1>
						{% if tips %}
					<div>{{tips}}</div>
						{% endif %}
					<form class="form" action="" method="post">
						{% csrf_token %}
						<div>用户名：<input type="text" name="username"></div>
						<div>密码：<input type="password" name="password"></div>
						{% if new_password %}
							<div>新密码：<input type="password" name="new_password"></div>
						{% endif %}
						<button type="submit" class="btn btn-primary btn-block">确定</button>
					</form>
					<div class="flex-left top-gap text-small">
						<div class="unit-2-3">
							<a href="{{ unit_2 }}">{{ unit_2_name }}</a>
						</div>
						<div class="unit-1-3 flex-right">
							<a href="{{ unit_1 }}">{{ unit_1_name }}</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

testview/user/templates/userForm.html
<html>
	<head>
		<title>用户注册</title>
		<link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
	</head>
	<body>
		<div class="flex-center">
			<div class="container">
				<div class="flex-center">
					<div class="unit-1-2 unit-1-on-mobile">
						<h1>MyDjango Auth</h1>
							{% if tips %}
						<div>{{ tips }}</div>
							{% endif %}
						<form action="" class="form" method="post">
							{% csrf_token %}
							<div>用户名：{{user.username}}</div>
							<div>邮箱：{{user.email}}</div>
							<div>手机号：{{user.mobile}}</div>
							<div>qq号：{{user.qq}}</div>
							<div>微信号：{{user.weChat}}</div>
							<div>密码：{{user.password1}}</div>
							<div>密码确认：{{user.password2}}</div>
							<button type="submit" class="btn btn-primary btn-block">注册</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

testview/user/templates/userPara.html
<html>
	<head>
		<title>找回密码</title>
		<link rel="stylesheet" href="https://unpkg.com/mobi.css/">
	</head>
	<body>
		<div class="flex-center">
			<div class="container">
				<div class="flex-center">
					<div class="unit-1-2 unit-1-on-mobile">
						<h1>MyDjango Auth</h1>
						{% if tips %}
						<div>{{ tips }}</div>
						{% endif %}
						<form action="" class="form" method="post">
							{% csrf_token %}
							<div>用户名：<input type="text" name="username" value="{{ username }}"></div>
							<div>验证码：<input type="text" name="VerificationCode"></div>
							{% if new_password %}
							<div>新密码：<input type="password" name="new_password"></div>
							{% endif %}
							<button type="submit" class="btn btn-primary btn-block">{{ button }}</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

testview/user/templates/userPerm.html
<html>
	<head>
		<link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
	</head>
	<body>
		<div class="flex-center">
			<div class="container">
				<div class="flex-center">
					<div class="unit-1-2 unit-1-on-mobile">
						<h1>MyDjango Auth</h1>
						{% if tips %}
						<div>{{tips}}</div>
						{% endif %}
						<form action="" class="form" method="post">
							{% csrf_token %}
							<div>用户名：<input type="text" name="username"></div>
							<div>用户名：<input type="password" name="password"></div>
							<button type="submit" class="btn btn-primary btn-block">确定</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

testview/user/templates/viewpara.html
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
</head>
<body>
	<ul id="cate_box" class="lf">
		{% for type in type_list %}
		<li>
			<h3><a href="#">{{type.type}}</a></h3>
			<p>
				{% for name in name_list %}
					{% if name.type == type.type %}
						<span>{{ name.name }}</span>
					{% endif %}
				{% endfor %}
			</p>
		</li>
		{% endfor %}
	</ul>
</body>
</html>